### ISSUE TITLE
H100 Hub Siren Broken After App Update to 2.10.0

### ISSUE THREAD

**Issue by ian27ukish** [petretiandrea/home-assistant-tapo-p100#572] opened 2023-10-15 18:42 UTC
-->

## Version of the integration

v2.10.0

## Configuration

H100 hub
Firmware - 1.3.9 Build 230522 Rel. 103415

```yaml
Not sure where this is, im looking in custom_components/tapo/ but cant see a yaml file....if you can point me in the right direction, happy to supply
```

## Describe the bug

Having updated to v2.10.0 of this plugin, the siren is no longer working from home assistant. 
siren.smart_hub_siren is showing the following error:
"This entity is no longer being provided by the tapo integration. If the entity is no longer in use, delete it in settings."
Its reporting temp and signal strength fine, and ive just added a temp sensor it picked up automatically as well.

## Debug log

2023-10-15 19:39:18.240 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-15 19:39:18.240 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-15 19:39:18.240 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration tapo_p100_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-15 19:39:18.241 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-15 19:39:25.557 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 802283280DCDFED039F461E7873765EE1E80D946
2023-10-15 19:39:25.577 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 802205DE6168F98E320DD51D692BB69B1E809919
2023-10-15 19:39:25.591 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 802272C2C275E7FCF4B6C3C8717AB1611FD277A9
2023-10-15 19:39:25.607 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 802DA9032B928746A2E3D48FE92DFD05216104B4
2023-10-15 19:39:26.207 WARNING (MainThread) [plugp100.api.tapo_client] Default protocol not working, fallback to KLAP ;)
2023-10-15 19:39:26.208 WARNING (MainThread) [plugp100.api.tapo_client] Default protocol not working, fallback to KLAP ;)
2023-10-15 19:39:26.242 WARNING (MainThread) [plugp100.api.tapo_client] Default protocol not working, fallback to KLAP ;)
2023-10-15 19:39:26.791 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.4.231: p100
2023-10-15 19:39:26.800 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.4.46: p100
2023-10-15 19:39:26.806 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.4.45: p100
2023-10-15 19:39:26.818 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.041 seconds (success: True)
2023-10-15 19:39:26.827 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.036 seconds (success: True)
2023-10-15 19:39:26.866 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.065 seconds (success: True)
2023-10-15 19:39:26.869 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.063 seconds (success: True)
2023-10-15 19:39:26.899 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.023 seconds (success: True)
2023-10-15 19:39:26.924 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.045 seconds (success: True)
2023-10-15 19:39:26.929 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.047 seconds (success: True)
2023-10-15 19:39:27.098 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.146 seconds (success: True)
2023-10-15 19:39:27.143 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.045 seconds (success: True)
2023-10-15 19:39:27.187 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.043 seconds (success: True)
2023-10-15 19:39:27.262 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.070 seconds (success: True)
2023-10-15 19:39:27.308 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.110 seconds (success: True)
2023-10-15 19:39:27.330 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.135 seconds (success: True)
2023-10-15 19:39:27.434 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.241 seconds (success: True)
2023-10-15 19:39:56.424 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.032 seconds (success: True)
2023-10-15 19:39:56.503 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.023 seconds (success: True)
2023-10-15 19:39:56.623 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.041 seconds (success: True)
2023-10-15 19:39:56.729 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.031 seconds (success: True)
2023-10-15 19:39:56.804 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.030 seconds (success: True)
2023-10-15 19:39:57.641 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.071 seconds (success: True)
2023-10-15 19:39:57.734 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.167 seconds (success: True)
2023-10-15 19:40:26.427 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.036 seconds (success: True)
2023-10-15 19:40:26.511 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.029 seconds (success: True)
2023-10-15 19:40:26.630 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.048 seconds (success: True)
2023-10-15 19:40:26.731 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.033 seconds (success: True)
2023-10-15 19:40:26.806 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.031 seconds (success: True)
2023-10-15 19:40:27.643 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.074 seconds (success: True)
2023-10-15 19:40:27.734 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.168 seconds (success: True)
2023-10-15 19:40:56.427 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.035 seconds (success: True)
2023-10-15 19:40:56.509 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.027 seconds (success: True)
2023-10-15 19:40:56.627 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.046 seconds (success: True)
2023-10-15 19:40:56.733 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.035 seconds (success: True)
2023-10-15 19:40:56.810 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.035 seconds (success: True)
2023-10-15 19:40:57.648 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.075 seconds (success: True)
2023-10-15 19:40:57.744 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.177 seconds (success: True)

**Comment by petretiandrea** [comment] 2023-10-16 18:11
Duplicate of #574

**Closed by petretiandrea** 2023-10-16 18:11 UTC
Labels: bug
