### ISSUE TITLE
'Current Energy' Entity no longer available

### ISSUE THREAD

**Issue by Hairsy07** [petretiandrea/home-assistant-tapo-p100#335] opened 2023-01-11 17:35 UTC
Since upgrading to the latest version on Sunday 8 Jan, there are two entities no longer available. They were working earlier that day. 

I'm afraid I'm quite new to Home Assistant and fairly inexperienced but I'm hoping that the information below is helpful.

Thank you.

Missing Entities
---------------
sensor.solar_socket_2_tapo_energy_monitor_plug_current_energy
and
sensor.solar_socket_2_tapo_energy_monitor_plug_this_month_energy

The first of these is the key one for me.

Error Message
--------------
"This entity is no longer being provided by the tapo integration. If the entity is no longer in use, delete it in settings."

Version of Integration
---------------------
1.3.7 (but error first occurred in 1.3.6)

Tapo Device
------------
P110
by TP-Link
Firmware: 1.1.6 Build 221114 Rel.203339
Hardware: 1.0

Log Entry
---------
Logger: custom_components.tapo.common_setup
Source: helpers/update_coordinator.py:201 
Integration: Tapo Controller ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/)) 
First occurred: 9 January 2023 at 6:53:10 pm (48 occurrences) 
Last logged: 5:23:10 pm

Error fetching tapo data: Unexpected exception:
 <!-- Before you open a new issue, search through the existing issues to see if others have had the same problem.

**Comment by petretiandrea** [comment] 2023-01-11 20:02
Please read here https://github.com/petretiandrea/home-assistant-tapo-p100/issues/321#issuecomment-1374841158. Closed as duplicate of #321

**Closed by petretiandrea** 2023-01-11 20:02 UTC
