### ISSUE TITLE
Click events (S200B)

### ISSUE THREAD

**Issue by Roedandan** [petretiandrea/home-assistant-tapo-p100#698] opened 2024-02-15 09:39 UTC
Issue #556 was marked not planned, but progress on it looked quite promising!
Is there any update on this?

Many thanks!

**Comment by Roedandan** [comment] 2024-02-15 09:40
https://github.com/mihai-dinculescu/tapo looks promising as well.

I do, however, see how polling rates would be too high for the hub.

**Comment by petretiandrea** [comment] 2024-02-24 10:17
> https://github.com/mihai-dinculescu/tapo looks promising as well.
> 
> I do, however, see how polling rates would be too high for the hub.

I've alredy implemented this feature at library level, it must be implemented to Home assistant too, but it's based on polling

**Comment by petretiandrea** [comment] 2024-02-24 10:18
Duplicate of #556

**Closed by petretiandrea** 2024-02-24 10:18 UTC
