### ISSUE TITLE
L900 LED strip when changing colour the plugin stops working period

### ISSUE THREAD

**Issue by bertybassett** [petretiandrea/home-assistant-tapo-p100#104] opened 2021-12-28 16:01 UTC
## Version of the custom_component

Version | core-2021.12.6
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 4.4.59+
CPU Architecture | x86_64
Timezone | Europe/London

-->

## Configuration

```yaml
nothing in yaml done form UI
```

## Describe the bug

L900 LED strip when changing colour or brightness the plugin stops working period
Nothing in logs a reboot fixes the issue.

## Debug log

```text

2021-12-28 15:55:06 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hive which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-28 15:55:06 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-28 15:55:06 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration tesla_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-28 15:55:06 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-28 15:55:06 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-28 15:55:06 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-28 15:55:51 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-12-28 15:55:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-12-28 15:55:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-12-28 15:55:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-12-28 15:55:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-12-28 15:55:52 WARNING (MainThread) [homeassistant.components.mqtt.light.schema_json] Invalid color mode received
2021-12-28 15:55:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-12-28 15:56:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'

```

**Comment by bertybassett** [comment] 2021-12-28 16:03
weird it has started working now.

**Comment by petretiandrea** [comment] 2021-12-29 15:17
Duplicate of #100

**Closed by petretiandrea** 2021-12-29 15:17 UTC
Labels: bug
