### ISSUE TITLE
Tapo T530 Bulb stopped working in Home Assistant Integ:v2.6.1 HA:2023.8.4

### ISSUE THREAD

**Issue by v966732** [petretiandrea/home-assistant-tapo-p100#490] opened 2023-08-25 06:51 UTC
My Tapo L530 bulb was working in Home Assistant till yesterday when it shows as unavailable. The bulb still works in the Tapo app.

I've deleted the device from HA and tried to add it back in but it will not connect - error log is below.

I'm using version 2.6.1 of the Tapo integration with HA version 2023.8.4
The Tapo L530 bulb is running firmware 1.1.0 Build 230721 Rel.224802

I've tried changing my Tapo account password, I've also deleted the bulb from within Tapo and re-added it, it has a static IP on my network.  My acount ID does not contain a capital letter.

Logs here:

```
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 182, in _try_setup_api
    .get_or_raise()
     ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/functional/tri.py", line 159, in get_or_raise
    raise self.value
plugp100.responses.tapo_exception.TapoException: Returned unknown error_code: 1003  msg: No message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 87, in async_step_user
    api = await self._try_setup_api(user_input)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 185, in _try_setup_api
    self._raise_from_tapo_exception(error)
  File "/config/custom_components/tapo/config_flow.py", line 194, in _raise_from_tapo_exception
    raise CannotConnect from exception
custom_components.tapo.errors.CannotConnect
```

**Comment by Acrosicious** [comment] 2023-08-25 08:06
HACS says I am using version **v1.6.1**, but I have the same issue with an L530. It worked fine 2 days ago. Might be unrelated to the version, or HACS shows the wrong version for me.

**Comment by Pugwash69** [comment] 2023-08-25 08:33
I have the same issue. All three L530 bulbs are unavailable in HA but working in the Tapo app and through google home. If I hover over the device in the "Needs Attention" box I see the message in the screenshot.
![Screenshot_20230825_093215](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/402003/6fa2ce85-391e-48ba-9b25-98fa72b89d44)

**Comment by Giuseppe197575** [comment] 2023-08-25 09:02
to me out of 3 lamps only 1 does not work and gives me the same message as yours

**Comment by ChrisCLewis** [comment] 2023-08-25 09:39
I have this exact issue. I thought it was just me. 

The error I receive when trying to re-add is:

     This error originated from a custom integration.

     Logger: custom_components.tapo.config_flow
     Source: custom_components/tapo/config_flow.py:87
     Integration: TP-Link Tapo (documentation, issues)
     First occurred: 24 August 2023 at 22:48:16 (9 occurrences)
     Last logged: 10:30:20

     Tapo exception 1003

It's worth noting that this only affects my L530E bulbs, and not any of the P100 smart plugs I have. All lights dropped off the network at the same time and rolling back to any of my backups hasn't had any effect.

The bulbs still show up within the Tapo app, although cannot be added to the Home Assistant integration.

**Comment by Av4K100** [comment] 2023-08-25 09:52
I am also getting this error after updating to the latest version

**Comment by antamuk** [comment] 2023-08-25 10:44
Similar problems here but I think I can add a little more detail:

6x L530 v2 Firmware 224802 all offline in HA but available in Tapo app
3x L510 v2 Firmware 224802 all offline in HA but available in Tapo app
but:
5x L510 v1 Firmware 1.2.4 working as expected in both HA & Tapo app 
plus an L900 & and L630 also working fine.

So it looks like the L510 & L530 v2 hardware only (& latest 224802 firmware)
These were all working normally until the night before last. No firmware updates were done on that night.
It was just after I'd updated to v2.6 of HA Tapo integration but BEFORE I'd updated to version 2.6.1

Currently wondering if there is something in firmware 224802 that is stopping HA Tapo v2.6.* re-authorising the bulbs.
Anyway thought it might be useful to share this info.

**Comment by Namirred** [comment] 2023-08-25 12:15
I'm having the same problem.

**Comment by carbolymer** [comment] 2023-08-25 17:58
Linking to the library issue where the error comes from: https://github.com/petretiandrea/plugp100/issues/116

**Comment by gwatuk** [comment] 2023-08-26 08:12
Me too - very annoying.

**Comment by petretiandrea** [comment] 2023-08-26 09:30
Duplicate of #482

**Closed by petretiandrea** 2023-08-26 09:30 UTC

**Comment by gwatuk** [comment] 2023-08-26 12:28
Fixed!
Well done @petretiandrea !
Thank you.
