### ISSUE TITLE
Current Energy is unavailible

### ISSUE THREAD

**Issue by wiklund75** [petretiandrea/home-assistant-tapo-p100#328] opened 2023-01-06 20:42 UTC
After last HA uppdate, the current energy meter for Tapo P115 is not availible anymore.

**Comment by ad-ha** [comment] 2023-01-07 15:01
Same thing here. All I got is this:

![image](https://user-images.githubusercontent.com/59612788/211157126-5b9a5a98-7002-40c7-ba7d-c9b945b6f3d9.png)

**Comment by petretiandrea** [comment] 2023-01-08 09:09
Close as duplicate of #321

**Closed by petretiandrea** 2023-01-08 09:09 UTC
