### ISSUE TITLE
Color/temp control not working on latest update

### ISSUE THREAD

**Issue by victorlucachi** [petretiandrea/home-assistant-tapo-p100#11] opened 2021-03-16 10:14 UTC
## Version of the custom_component

Latest

## Configuration

```yaml
N/A
```

## Describe the bug

Brightness still works, no color or temp control though

## Debug log

```text

Logger: homeassistant.components.websocket_api.http.connection
Source: components/light/__init__.py:485
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:33:13 AM (11 occurrences)
Last logged: 12:01:59 PM

[139913444255728] type NoneType doesn't define __round__ method
[139913468791728] type NoneType doesn't define __round__ method
[139913453106128] type NoneType doesn't define __round__ method
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 235, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/config/custom_components/tapo/light.py", line 75, in async_turn_on
    await self._tapo_coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 200, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 260, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 485, in state_attributes
    data[ATTR_HS_COLOR] = (round(hs_color[0], 3), round(hs_color[1], 3))
TypeError: type NoneType doesn't define __round__ method

```

```text
Logger: homeassistant.components.light
Source: components/light/__init__.py:485
Integration: Light (documentation, issues)
First occurred: 11:32:05 AM (2 occurrences)
Last logged: 11:32:05 AM

Error adding entities for domain light with platform tapo
Error while setting up tapo platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 485, in state_attributes
    data[ATTR_HS_COLOR] = (round(hs_color[0], 3), round(hs_color[1], 3))
TypeError: type NoneType doesn't define __round__ method
```

**Comment by petretiandrea** [comment] 2021-03-16 12:45
As I expected there is some trouble. You can try to get me the state of your lamp using this docker container command
```docker
docker run --rm -e TAPO_ADDRESS=your_tapo_ip -e TAPO_USERNAME=your_username -e TAPO_PASSWORD=your_password petretiandrea/tapo-utils
```

Post here the JSON output, remove location for privacy reason :)

**Comment by victorlucachi** [comment] 2021-03-16 13:04
Here's the output:

```
Traceback (most recent call last):
  File "//./main.py", line 17, in <module>
9f3d2d3ae89b91d477b0ffbd51a6aff258ea260c
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "//./main.py", line 12, in main
    await sw.login()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 70, in login
    await self._login_request(self.username, self.password)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 191, in _login_request
    self.token = decrypted_inner_response['result']['token']
KeyError: 'result'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f4e1d62cee0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f4e1d1f5580>, 12475.535023032)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f4e1d62cf40>
```

**Comment by petretiandrea** [comment] 2021-03-16 13:38
Are you sure about your login data and ip address? This error is caused due to an invalid response from login method

**Comment by victorlucachi** [comment] 2021-03-16 13:41
Yes, local IP address of the bulbs is correct (tried it with both of my bulbs) as well as password and email. No quotes used in the command.

**Comment by petretiandrea** [comment] 2021-03-16 16:13
This is strange. Try this, create a folder and inside it use this command for create a python venv
`python3 -m venv venv`

Now enable the venv (./venv/bin/activate for linux users). Install two deps
`pip install asyncio plugp100`

Now create a python file with this snippet of code

```python
import asyncio
from plugp100 import TapoApiClient

async def main():
    # create generic tapo api
    sw = TapoApiClient("<ip>", "<username>", "<password>")
    await sw.login()
    state = await sw.get_state()
    print(state.state)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.run_until_complete(asyncio.sleep(0.1))
loop.close()
```

**Comment by braymullo** [comment] 2021-03-17 11:04
Hey! Easier to chat here than on community.homeassistant.

Ok so your latest version works again with brightness, and I can see the temp slider and colour wheel but initial testing has shown it not to work. Included below is a screen recording of the issue so you can see, and also a dump of my log pertaining to this issue. The decrypt fail is the common one, but I see some others in there too which may be of value to you.

- Changing the brightness slider works
- Changing the colour temp slider glitches out as you will see, it does however push a colour temp of 2500k to my bulb, which I can monitor in my Tapo iOS app. This is the only value it pushes regardless of what temp I select in the lovelace card.
- The colour wheel gives us a Decrpytion failed error.

And thanks again!

Video: [Here](https://we.tl/t-eozukqjnYv)

Log: [Here](https://pastebin.com/DxPK97GM)
password: tapotest

**Comment by petretiandrea** [comment] 2021-03-17 11:13
Thank you for the video and log. Can you try to use this snippet of code as described above:
```
import asyncio
from plugp100 import TapoApiClient

async def main():
    # create generic tapo api
    sw = TapoApiClient("<ip>", "<username>", "<password>")
    await sw.login()
    state = await sw.get_state()
    print(state.state)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.run_until_complete(asyncio.sleep(0.1))
loop.close()
```

With a full representation of state I think that I can fix the problems

**Comment by braymullo** [comment] 2021-03-17 11:47
Sure thing, 

bashing into my HASS Docker container (alpine) gives an error on  `pip install asyncio plugp100`
I need to install these dependencies first
`apk add --no-cache --virtual .build-deps gcc musl-dev`
`pip install cython`
Then `pip install asyncio plugp100` works. Just an FYI for others

Here is the output of the test python file

`2aee0bfc79ee441b0c30e1fe11e73d57d1a5f128
{'device_id': '80235BB614053ACC4A9E499A85827FC91D7955EE', 'fw_ver': '1.1.9 Build 20210122 Rel. 56165', 'hw_ver': '1.0.0', 'type': 'SMART.TAPOBULB', 'model': 'L530 Series', 'mac': '60-32-B1-FD-3E-17', 'hw_id': '93F94D88DA9499F43B929DD38EBDF09A', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': 'D042998E924F77C9E23A75966003ADD8', 'specs': 'EU', 'lang': 'en_US', 'device_on': True, 'on_time': 2712, 'overheated': False, 'nickname': 'VGFwbyA1MzBlIEJlZHJvb20=', 'avatar': 'hang_lamp_1', 'brightness': 100, 'dynamic_light_effect_enable': False, 'color_temp': 2500, 'default_states': {'type': 'last_states', 'state': {'brightness': 100, 'color_temp': 2500}}, 'time_diff': 60, 'region': 'removed', 'longitude': removed, 'latitude': removed, 'has_set_location_info': True, 'ip': 'removed', 'ssid': 'removed', 'signal_level': 2, 'rssi': -60}
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xb567bda8>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0xb563d178>, 1713.863504975)]']
connector: <aiohttp.connector.TCPConnector object at 0xb5697130>`

**Comment by petretiandrea** [comment] 2021-03-17 11:51
Perfect, thank you so much. Now try to set a color to bulb using tapo app and execute again the snippet and post here the output.

**Comment by braymullo** [comment] 2021-03-17 11:53
Sure, here is Red @ 80% brightness, set via the Tapo iOS app.

`2aee0bfc79ee441b0c30e1fe11e73d57d1a5f128
{'device_id': '80235BB614053ACC4A9E499A85827FC91D7955EE', 'fw_ver': '1.1.9 Build 20210122 Rel. 56165', 'hw_ver': '1.0.0', 'type': 'SMART.TAPOBULB', 'model': 'L530 Series', 'mac': '60-32-B1-FD-3E-17', 'hw_id': '93F94D88DA9499F43B929DD38EBDF09A', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': 'D042998E924F77C9E23A75966003ADD8', 'specs': 'EU', 'lang': 'en_US', 'device_on': True, 'on_time': 232, 'overheated': False, 'nickname': 'VGFwbyA1MzBlIEJlZHJvb20=', 'avatar': 'hang_lamp_1', 'brightness': 80, 'dynamic_light_effect_enable': False, 'hue': 0, 'saturation': 100, 'color_temp': 0, 'default_states': {'type': 'last_states', 'state': {'brightness': 80, 'hue': 0, 'saturation': 100, 'color_temp': 0}}, 'time_diff': 60, 'region': 'removed', 'longitude': removed, 'latitude': removed, 'has_set_location_info': True, 'ip': 'removed', 'ssid': 'removed', 'signal_level': 2, 'rssi': -60}
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xb5676df0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0xb56381a8>, 2141.669250984)]']
connector: <aiohttp.connector.TCPConnector object at 0xb56901a8>`

**Comment by braymullo** [comment] 2021-03-17 12:03
Here is HEX colour FF7B42, so you can see how the two outputs change, if that's of interest

[Screengrab](https://imgur.com/jKetTnf)

`2aee0bfc79ee441b0c30e1fe11e73d57d1a5f128
{'device_id': '80235BB614053ACC4A9E499A85827FC91D7955EE', 'fw_ver': '1.1.9 Build 20210122 Rel. 56165', 'hw_ver': '1.0.0', 'type': 'SMART.TAPOBULB', 'model': 'L530 Series', 'mac': '60-32-B1-FD-3E-17', 'hw_id': '93F94D88DA9499F43B929DD38EBDF09A', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': 'D042998E924F77C9E23A75966003ADD8', 'specs': 'EU', 'lang': 'en_US', 'device_on': True, 'on_time': 645, 'overheated': False, 'nickname': 'VGFwbyA1MzBlIEJlZHJvb20=', 'avatar': 'hang_lamp_1', 'brightness': 100, 'dynamic_light_effect_enable': False, 'hue': 18, 'saturation': 74, 'color_temp': 0, 'default_states': {'type': 'last_states', 'state': {'brightness': 100, 'hue': 18, 'saturation': 74, 'color_temp': 0}}, 'time_diff': 60, 'region': 'removed', 'longitude': removed, 'latitude': removed, 'has_set_location_info': True, 'ip': 'removed', 'ssid': 'V29lc3R5bkxpbmsyNA==', 'signal_level': 2, 'rssi': -60}
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xb570fe80>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0xb56d0208>, 2554.381854496)]']
connector: <aiohttp.connector.TCPConnector object at 0xb5728238>`

**Comment by petretiandrea** [comment] 2021-03-17 12:16
Thank you again, I will work for a fix

**Comment by petretiandrea** [comment] 2021-03-17 14:21
Thanks to JSON state I think that the problem with color temperature is fixed. Try It. I've suspended the color feature for now, in a few days I will fix it too.

**Comment by braymullo** [comment] 2021-03-17 15:12
Awesome thanks! You're a legend

The temp works now, if I adjust it a lot and quite quickly I get a decryption failed error. But it rights itself after a while.

**Comment by petretiandrea** [comment] 2021-03-18 23:09
I pushed some changes related to color support, before merge into main branch please try it from color-support branch   #16

**Comment by braymullo** [comment] 2021-03-19 06:52
Sure, is there a best practise to try this branch via hacs? Or should I just replace custom_components and restart?

**Comment by petretiandrea** [comment] 2021-03-19 07:42
Actually just add another repository using the URL that refers to color_support branch. For next times, I will add to hacs a sort of "beta" switch

**Comment by braymullo** [comment] 2021-03-19 09:26
Deleted integration
Deleted Previous HACS repo
Restart
I added the following repo: https://github.com/petretiandrea/home-assistant-tapo-p100/tree/color-support
Installed
Restart
Added Tapo 530
I get Brightness and Colour Temp, no colour wheel 

Hope that helps :)

**Comment by petretiandrea** [comment] 2021-03-19 09:53
Sorry this is not working. I verified now that HACS go to default branch which is main in this case. I will think a smarter method to test the pull request. For now try to install it manually, clone the repo from color-support branch :(

**Comment by braymullo** [comment] 2021-03-19 10:12
Removed HACS version
Deleted integration
Copied custom_components/tapo from colour branch into custom_components
Restart
Added integration

Colour wheel appears but when moving it around I get Decryption failed error and then server disconnection error. 

Both logs you can find here: https://pastebin.com/Ta0ZkGyt
Pass: tapotest

**Comment by petretiandrea** [comment] 2021-03-19 10:18
You can try to use my previous piece of code? You try adding this piece of code to set the bulb to a specific color
```python
await sw.set_hue_saturation(18, 74)
```

If you receive a decryption error, I think that the problem is into plugp100 implementation

**Comment by braymullo** [comment] 2021-03-19 10:23
That worked! added it like this 

`import asyncio
from plugp100 import TapoApiClient

async def main():
    # create generic tapo api
    sw = TapoApiClient("removed", "removed", "removed")
    await sw.login()
    state = await sw.get_state()
    await sw.set_hue_saturation(18, 74)
    print(state.state)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.run_until_complete(asyncio.sleep(0.1))
loop.close()`

And she turned a lovely reddish orange. 

Now not sure why Home Assistant is giving decryption errors

**Comment by petretiandrea** [comment] 2021-03-19 10:25
I forgot to add lambda to `change_color` method. I've pushed now, please try again

**Comment by braymullo** [comment] 2021-03-19 10:31
You've cracked it! Well done!

Works perfectly

**Comment by petretiandrea** [comment] 2021-03-19 10:32
Thank you too. Now I merge the branch into the main branch. You can use it from Hacs  :)

**Closed** 2021-03-19 10:33 UTC

**Comment by phets526** [comment] 2023-05-17 06:25
Is there anyway to downgrade or rollback our current version to 1.8 or whatever it is that had it working?
