### ISSUE TITLE
Tapo P115 Entity not updating

### ISSUE THREAD

**Issue by manuzzo24** [petretiandrea/home-assistant-tapo-p100#265] opened 2022-10-20 18:39 UTC
Hello,
today I have received my Tapo P115. Configured and then updated the firmware from the app (1.1.2 Build 220930 Rel. 144500).
I then added it to HA through HACS, but it seems that the entity doesn't update its values.

The only way to update the values is to reload the Integration from the Settings, but it's of course not useful. As you can see the line is always straight, the only time it changes in the graph is when I reloaded the Integration. Everything is working fine in the Tapo app and the Energy changes each second or so.
Is anyone having this problem?

![P115](https://user-images.githubusercontent.com/94800007/197030894-a0a8cb65-9886-4e37-978b-b81e96c26ee8.png)
![Graph](https://user-images.githubusercontent.com/94800007/197030887-e2d1b207-7120-4ec4-902e-009cb692bd90.png)

**Comment by ElyFNV** [comment] 2022-10-21 04:36
Ehy! Same problem with Tapo P110! The new firmware update has bene released yesterday! Now the smart plugs are not updating their values.
You can find the issue opened in this repository.
We will wait for a fix!

**Comment by petretiandrea** [comment] 2022-10-21 18:03
Seems to be related to new firmware release by tapo

**Comment by petretiandrea** [comment] 2022-10-21 18:03
Duplicate of #264

**Closed by petretiandrea** 2022-10-21 18:03 UTC
