### ISSUE TITLE
Tapo P110 data missing

### ISSUE THREAD

**Issue by ElyFNV** [petretiandrea/home-assistant-tapo-p100#281] opened 2022-11-21 15:00 UTC
Hi everyone!
I have 10 Tapo P110 smart plug, with energy monitoring.
I integrated them the 6th of october 2022. However, I don't know why but I cannot see data before 11st of november 2022. Such as if the data before that date had been deleted... I use month_energy sensors...
Has this happened to anyone else too?  Do you know why I can't view data before that date?  I noticed that the problem is not with Home Assistant since even on the Tapo application I don't have the data before November 11th, when in reality I have been using the plugs since October 6th.
Other strange thing... In Tapo app I see energy data for dates that have not yet passed, such as December 1, 2022 (as you can see from the attached photos).
However, if I go to see the calendar it no longer shows me future dates, but you can still see how the data for October is missing even if it somehow tells me the cost for the month of October.  Absolutely nothing maked sense!!!
Anyone can help me? Please!
![Screenshot_20221121-155939](https://user-images.githubusercontent.com/37159948/203087254-b7680ae4-5ba0-479b-9575-48c5d108f7c5.png)
![Screenshot_20221121-155959](https://user-images.githubusercontent.com/37159948/203087298-24f17f51-fe41-4737-8476-1e2d502c735a.png)

**Comment by novotnej** [comment] 2022-11-22 14:17
Hello, this might be coming from the Tapo device - in the latest firmware update, there was a notice, that historical data might be deleted. If you performed a firmware update recently, this might be it.

**Comment by petretiandrea** [comment] 2022-11-25 07:47
Related to #264

**Comment by petretiandrea** [comment] 2022-12-30 12:09
Duplicate of #264

**Closed by petretiandrea** 2022-12-30 12:09 UTC
