### ISSUE TITLE
P110 not showing any sensor data after update to 2.0.0

### ISSUE THREAD

**Issue by Dirkhaan** [petretiandrea/home-assistant-tapo-p100#424] opened 2023-07-06 08:44 UTC
## Version of the integration
2.0.0

## Configuration
3 x TAPO P110 HW Version 1.0 FW Version 1.2.3 Build 230425 Rel. 142542

## Describe the bug

The  sensors Current Power, Month Energy, Month Runtime, Today Energy and Today runtime all state unknown after update to 2.0.0 

I have deleted and manually added them again, als rebooted several times, but state remains unknown.

## Debug log

2023-07-06 10:38:12.200 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.044 seconds (success: True)
2023-07-06 10:38:12.416 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.048 seconds (success: True)
2023-07-06 10:38:12.509 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.044 seconds (success: True)
2023-07-06 10:38:16.112 INFO (MainThread) [custom_components.tapo] Unloaded entry for 27c82b3b10884380c3c1d81e18424d92
2023-07-06 10:38:16.122 DEBUG (MainThread) [custom_components.tapo.common_setup] Creating new API to create a coordinator
2023-07-06 10:38:16.364 INFO (MainThread) [custom_components.tapo.coordinators] Login to 192.168.1.81, success: Right True
2023-07-06 10:38:16.409 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.1.81: p110
2023-07-06 10:38:16.457 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.047 seconds (success: True)
2023-07-06 10:38:16.534 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.048 seconds (success: True)
2023-07-06 10:38:19.160 INFO (MainThread) [custom_components.tapo] Unloaded entry for 1161cd785ad421b6818c60d4e1a4d46a
2023-07-06 10:38:19.172 DEBUG (MainThread) [custom_components.tapo.common_setup] Creating new API to create a coordinator
2023-07-06 10:38:19.361 INFO (MainThread) [custom_components.tapo.coordinators] Login to 192.168.1.63, success: Right True
2023-07-06 10:38:19.398 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.1.63: p110
2023-07-06 10:38:19.445 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.046 seconds (success: True)
2023-07-06 10:38:19.528 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.051 seconds (success: True)
2023-07-06 10:38:22.548 INFO (MainThread) [custom_components.tapo] Unloaded entry for 09566cca8633c6060c878def59a55e83
2023-07-06 10:38:22.552 DEBUG (MainThread) [custom_components.tapo.common_setup] Creating new API to create a coordinator
2023-07-06 10:38:22.753 INFO (MainThread) [custom_components.tapo.coordinators] Login to 192.168.1.82, success: Right True
2023-07-06 10:38:22.797 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.1.82: p110
2023-07-06 10:38:22.844 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.046 seconds (success: True)
2023-07-06 10:38:22.923 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.047 seconds (success: True)

**Comment by XRedShark** [comment] 2023-07-06 08:47
Also P115

**Comment by Gilbertonl** [comment] 2023-07-06 08:56
Same problem here.

**Comment by hartitman** [comment] 2023-07-06 09:00
Same for me, tried deletion and re-adding but still the same. I also noticed a firmware update avaliable for the plugs, I did this and restarted both plug and HA but still the same, No sensor data

**Comment by Dirkhaan** [comment] 2023-07-06 09:22
As a workaround for now, i have deleted all the files in the /config/custom_components/tapo folder. After that i re-installed the 1.7.1 version and restarted HA. This has, for now, resolved my issue.

**Comment by lyricnz** [comment] 2023-07-06 09:30
Probable duplicate of #423

**Comment by hartitman** [comment] 2023-07-06 09:44
Until a fix is avalaible I am restoring from backup

**Comment by spetrie13** [comment] 2023-07-06 10:42
Fix in https://github.com/petretiandrea/home-assistant-tapo-p100/issues/423

Works for me

**Closed** 2023-07-06 19:46 UTC
